Update MinIO and mc to handle panfs path for buckets
panasasinc/minio-go pull request #2
Opened 2022-11-29 14:34 UTC by dmitrizpanasas

This PR updates mb and stat commands allowing client to gather PanFS path and make bucket with additional metadata field

2022-11-30 10:44 UTC, lech-lorens-epam requested changes

2022-11-30 10:44 UTC, lech-lorens-epam commented on api-bucket-panfs-path.go
> + * MinIO Go Library for Amazon S3 Compatible Cloud Storage
@yauhen-matsiushonak do we already know what should be placed here?

2022-11-30 10:44 UTC, lech-lorens-epam commented on api-put-bucket.go
> +		reqMetadata.customHeader = headers
This can overwrite `customHeader` set on line 71 if `objectLockEnabled` is set as well.

2022-12-02 13:29 UTC, lech-lorens-epam approved these changes

2022-12-02 14:02 UTC, akhmialevskiy approved these changes

2022-12-06 16:40 UTC, merged